Fix update master to upstream
bizimply/jquery-fileupload-rails pull request #2
Opened 2024-05-13 16:38 UTC by zeiad133

2024-05-14 06:25 UTC, mikabogumil requested changes
I can see that the recent one is 1.13.3:
https://jqueryui.com/download/

I can also see that we had just `widget` here, while the new code provides tons of other functionalities that were not here before (means that we don't need them). Can we try to use newer version as well as only include what we need? thanks

2024-05-14 09:22 UTC, mikabogumil approved these changes
Looks perfect :)

2024-05-14 09:23 UTC, mikabogumil commented
DO NOT DEPLOY IT UNTIL WE GOT IT TESTED ON SHIFTDIARY.COM :)

2024-05-24 09:15 UTC, Fatma-Mohammed approved these changes

2024-05-27 08:56 UTC, merged